language: php

php:
  - "7.1"


before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  # Install JSCS: JavaScript Code Style checker.
  # @link http://jscs.info/
  - if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
  # Install JSHint, a JavaScript Code Quality Tool.
  # @link http://jshint.com/docs/
  - if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi

services:
  - mysql

script:
- vendor/bin/phpunit
