language: php

php:
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

services:
  - mysql

script:
- vendor/bin/phpunit
- if [[ $TRAVIS_PHP_VERSION != hhv* ]] ; then php bin/phpcs --config-set php_path php; fi
